[package]
name = "embed-openai"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
# Shared Golem utilities (config loader, HTTP client, retries, metrics, etc.)
golem-common = { path = "../golem-common" }

# Async runtime
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

# HTTP + JSON
reqwest = { version = "0.11", features = ["rustls-tls", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# (Optional) for any tracing/logging you might add
tracing = "0.1"

[build-dependencies]
# Generates Rust bindings for both embed.wit and golem-durability.wit
wit-bindgen-preview2 = { version = "0.19.0", features = ["rust", "imports"] }

[dev-dependencies]
httpmock = "0.6"                  # lightweight HTTP server for mocking
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[profile.release]
opt-level = "z"
lto = true
